name: Format and style

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  style-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install clang-tools
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy clang-format

    - name: Run clang-tidy
      run: |
        find . -name "*.cpp" -o -name "*.h" -o -name "*.hpp" | \
        xargs clang-tidy --config-file=.clang-tidy --warnings-as-errors='*'

    - name: Check clang-format
      run: |
        find . -name "*.cpp" -o -name "*.h" -o -name "*.hpp" | \
        xargs clang-format --dry-run --Werror --style=file
