name: Windows Deploy
on: [workflow_dispatch]
jobs:
  Build-Windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: CMake build
        run: |
          mkdir cmake_build
          cd cmake_build
          cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -A x64 ..
          cmake --build . --config Release --parallel -- /clp:ErrorsOnly
          ctest --output-on-failure
     
      - name: Package
        run: |
          $curDir = pwd
          cd cmake_build
          & "C:/Program Files (x86)/Inno Setup 6/iscc.exe" "$curDir\\cmake_build\\installer.iss"

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: WindowsBuild
          path: "cmake_build/*.exe"

      - name: Upload info
        uses: actions/upload-artifact@v4
        with:
          name: WindowsText
          path: "cmake_build/*.txt"

  Deploy-Exe:
    runs-on: ubuntu-latest
    needs: Build-Windows
    steps:
      - name: Download artefact
        uses: actions/download-artifact@v4
        with:
          name: WindowsBuild

      - name: Download info
        uses: actions/download-artifact@v4
        with:
          name: WindowsText

      - name: Upload to storage
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.R2_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET }}
          export AWS_DEFAULT_REGION=auto
          PRODUCT_VERSION=$(cat ./version.txt)
          PROJECT_NAME=$(cat ./project_name.txt)
          aws --endpoint-url ${{ secrets.R2_ENDPOINT }} s3 cp "./${PROJECT_NAME} Installer.exe" s3://vitalaudiobuilds/${{ github.repository }}/$PRODUCT_VERSION/
